# Generated by Django 6.0.1 on 2026-01-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0002_userprofile_face_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='captured_face',
            field=models.ImageField(blank=True, null=True, upload_to='captured_faces/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='face_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
