# Generated by Django 6.0.1 on 2026-01-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0004_userprofile_address_userprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='snapshot_base64',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='captured_face_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
