# Generated by Django 6.0.1 on 2026-01-21 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0006_userprofile_designation_userprofile_employee_id'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE VIEW manage_employees_view AS
            SELECT 
                au.id as user_id,
                au.username, 
                au.email, 
                au.first_name, 
                au.last_name,
                p.employee_id, 
                p.designation, 
                p.phone_number,
                p.address,
                p.date_of_birth,
                p.marital_status,
                CASE WHEN p.has_setup_face = 1 THEN 'Enrolled' ELSE 'Not Set' END as face_status,
                CASE WHEN p.is_locked = 1 THEN 'Locked' ELSE 'Active' END as account_status,
                au.last_login
            FROM 
                auth_user au
            JOIN 
                access_control_userprofile p ON au.id = p.user_id
            WHERE 
                p.is_admin_user = 0;
            """,
            reverse_sql="DROP VIEW IF EXISTS manage_employees_view;"
        )
    ]
