# Generated by Django 6.0.1 on 2026-01-21 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0006_userprofile_designation_userprofile_employee_id'),
    ]

    operations = [
        migrations.RunSQL(
            "",
            reverse_sql=""
        )
    ]
