# Generated by Django 6.0.1 on 2026-01-21 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0007_create_manage_employees_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
