# Generated by Django 6.0.1 on 2026-02-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0009_alter_department_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
