# Generated by Django 6.0.1 on 2026-02-20 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0011_userprofile_basic_salary_userprofile_cca_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='hourly_rate',
            new_name='daily_rate',
        ),
    ]
